server:
  port: 89
spring:
  datasource:
    url: jdbc:mysql://192.168.40.128:3308/dockerlearn?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver